import {ActivationStatus} from "../../models/enums/activation-status.js";
export const TABLE_NAME = "invitations";
export const COLUMN_ID = "id";
export const COLUMN_UUID = "uuid";
export const COLUMN_SENDER_ID = "sender_id";
export const COLUMN_RECIPIENT_EMAIL = "recipient_email";
export const COLUMN_CREATED_AT_UTC="created_at_utc";
export const COLUMN_EXPIRES_AT_UTC = "expires_at_utc";
export const COLUMN_INVITATION_STATUS="invitation_status";
export const ALIAS="i"
export const ALIAS_COLUMN_DELIVERY_STATUS=`"deliveryStatus"`;
export const ALIAS_COLUMN_CREATED_AT_UTC=`"createdAtUTC"`;
export const ALIAS_COLUMN_EXPIRES_AT_UTC = `"expiresAtUTC"`;
export const ALIAS_COLUMN_RECIPIENT_ID = `"recipientId"`;
export const ALIAS_COLUMN_SENDER_ID=`"senderId"`
export const ALIAS_COLUMN_INVITATION_STATUS=`"invitationStatus"`;
export const ALIAS_SENDER_UUID=`"senderUuid"`;
export const ALIAS_SENDER_FIRST_NAME=`"senderFirstName"`;
export const ALIAS_SENDER_LAST_NAME=`"senderLastName"`;
export const ALIAS_SENDER_EMAIL=`"senderEmail"`;
export const ALIAS_SENDER_PROFILE_PICTURE_PATH=`"senderProfilePicturePath"`;
export const ALIAS_RECIPIENT_UUID=`"recipientUuid"`;
export const ALIAS_RECIPIENT_FIRST_NAME=`"recipientFirstName"`;
export const ALIAS_RECIPIENT_LAST_NAME=`"recipientLastName"`;
export const ALIAS_RECIPIENT_EMAIL=`"recipientEmail"`;
export const ALIAS_RECIPIENT_PROFILE_PICTURE_PATH=`"recipientProfilePicturePath"`;
