export const TABLE_NAME = "locations";
export const COLUMN_ID = "id";
export const COLUMN_NAME = "name";
export const COLUMN_LOCATION_ON_MAP = "location_on_map";
export const COLUMN_CREATED_AT_UTC= "created_at_utc";
export const COLUMN_UPDATED_AT_UTC = "updated_at_utc";
export const ALIAS_COLUMN_CREATED_AT_UTC= `"locationCreatedAtUTC"`//Postgre lowers unquoted "" uppercase words ;
export const ALIAS_COLUMN_UPDATED_AT_UTC = `"locationUpdatedAtUTC"`;
export const ALIAS_COLUMN_NAME = `"locationName"`;
export const ALIAS_LONGITUDE = "longitude";
export const ALIAS_LATITUDE = "latitude";
export const ALIAS="l"