export const TABLE_NAME = "organizations";
export const COLUMN_ID = "id";
export const COLUMN_UUID = "uuid";
export const COLUMN_NAME = "name";
export const COLUMN_EMAIL = "email";
export const COLUMN_PHONE_NUMBER = "phone_number";
export const COLUMN_BIO = "bio";
export const COLUMN_LOCATION_ID = "location_id";
export const COLUMN_PROFILE_PICTURE_PATH="profile_picture_path";
export const COLUMN_CREATED_AT_UTC="created_at_utc";
export const COLUMN_UPDATED_AT_UTC = "updated_at_utc";
export const COLUMN_STATUS="status";
export const ALIAS="o"
export const ALIAS_COLUMN_PHONE_NUMBER=`"phoneNumber"`;
export const ALIAS_COLUMN_PROFILE_PICTURE_PATH=`"profilePicturePath"`;
export const ALIAS_COLUMN_CREATED_AT_UTC=`"createdAtUTC"`;
export const ALIAS_COLUMN_UPDATED_AT_UTC = `"updatedAtUTC"`;
export const ALIAS_COLUMN_NAME = `"organizationName"`;
export const ALIAS_COLUMN_ORGANIZATION_UUID = `"organizationUuid"`;