export const TABLE_NAME = "users";
export const COLUMN_ID = "id";
export const COLUMN_UUID = "uuid";
export const COLUMN_FIRST_NAME = "first_name";
export const COLUMN_LAST_NAME = "last_name";
export const COLUMN_EMAIL = "email";
export const COLUMN_UID="firebase_uid";
export const COLUMN_PROFILE_PICTURE_PATH = "profile_picture_path";
export const COLUMN_CREATED_AT_UTC = "created_at_utc";
export const COLUMN_UPDATED_AT_UTC = "updated_at_utc";
export const COLUMN_LANGUAGE="language";
export const COLUMN_ORGANIZATION_ID="organization_Id";
export const COLUMN_ROLE="role";
export const COLUMN_STATUS="status";
export const ALIAS="u"
export const SECONDARY_ALIAS="u1"
export const THIRD_ALIAS="u2"
export const ALIAS_COLUMN_FIRST_NAME = `"firstName"`;
export const ALIAS_COLUMN_LAST_NAME = `"lastName"`;
export const ALIAS_COLUMN_PROFILE_PICTURE_PATH = `"profilePicturePath"`;
export const ALIAS_COLUMN_CREATED_AT_UTC = `"createdAtUTC"`;
export const ALIAS_COLUMN_UPDATED_AT_UTC = `"updatedAtUTC"`;
export const ALIAS_COLUMN_ORGANIZATION_ID = `"organizationId"`;
export const ALIAS_COLUMN_USER_UUID = `"userUUID"`;
export const ALIAS_TOTAL_NUMBER_OF_USERS = `"totalNumberOfUsers"`;
export const SORT_BY_NAME = "name";
export const SORT_BY_CREATED_AT_UTC = "createdAtUTC";