import {RoomResponse, Room, UpdateRoom,CreateRoom} from "../models/room.model.js"
import {pool} from "../databases/postgre-connection.js"
import {
    TABLE_NAME,
    COLUMN_ID,
    COLUMN_UUID,
    COLUMN_CREATED_AT_UTC,
    COLUMN_EXPIRES_AT_UTC,
    COLUMN_SENDER_ID,
    COLUMN_INVITATION_STATUS,
    ALIAS,
    ALIAS_COLUMN_CREATED_AT_UTC,
    ALIAS_COLUMN_DELIVERY_STATUS,
    ALIAS_COLUMN_EXPIRES_AT_UTC,
    ALIAS_COLUMN_RECIPIENT_ID,
    ALIAS_COLUMN_SENDER_ID,
    ALIAS_COLUMN_INVITATION_STATUS, ALIAS_SENDER_UUID, ALIAS_SENDER_FIRST_NAME, ALIAS_SENDER_LAST_NAME,
    ALIAS_SENDER_EMAIL, ALIAS_RECIPIENT_UUID, ALIAS_RECIPIENT_FIRST_NAME, ALIAS_RECIPIENT_LAST_NAME,
    ALIAS_RECIPIENT_EMAIL, ALIAS_SENDER_PROFILE_PICTURE_PATH, ALIAS_RECIPIENT_PROFILE_PICTURE_PATH,
    COLUMN_RECIPIENT_EMAIL
} from "../databases/contracts/invitation.contract.js"
import {
    TABLE_NAME as ORGANIZATION_TABLE_NAME,
    ALIAS as ORGANIZATION_ALIAS,
    COLUMN_ID as ORGANIZATION_COLUMN_ID,
    COLUMN_NAME as ORGANIZATION_COLUMN_NAME,
    ALIAS_COLUMN_ORGANIZATION_UUID as ORGANIZATION_ALIAS_COLUMN_UUID,
    ALIAS_COLUMN_NAME as ORGANIZATION_ALIAS_COLUMN_NAME,
    ALIAS_COLUMN_PROFILE_PICTURE_PATH as ORGANIZATION_ALIAS_COLUMN_PROFILE_PICTURE_PATH,
    COLUMN_UUID as ORGANIZATION_COLUMN_UUID, COLUMN_PROFILE_PICTURE_PATH, ALIAS_COLUMN_ORGANIZATION_UUID,
} from "../databases/contracts/organization.contract.js"
import {
    COLUMN_ID as USER_COLUMN_ID,
    COLUMN_UUID as USER_COLUMN_UUID,
    TABLE_NAME as USER_TABLE_NAME,
    ALIAS as USER_SENDER_ALIAS,
    SECONDARY_ALIAS as USER_RECIPIENT_ALIAS, COLUMN_ORGANIZATION_ID as USER_COLUMN_ORGANIZATION_ID,
    COLUMN_FIRST_NAME as USER_COLUMN_FIRST_NAME,
    COLUMN_LAST_NAME as USER_COLUMN_LAST_NAME,
    COLUMN_EMAIL as USER_COLUMN_EMAIL,
    COLUMN_PROFILE_PICTURE_PATH as USER_COLUMN_PROFILE_PICTURE_PATH,

} from "../databases/contracts/user.contract.js"
import {QueryResult} from "pg";
import {InvitationResponse, Invitation, CreateInvitation,UpdateInvitation} from "../models/invitation.model.js";
import {CreateService, Service, ServiceResponse, UpdateService} from "../models/service.model.js";
import {InvitationStatus} from "../models/enums/invitation-status.js";
export async function findAll(organizationUuid:string):Promise<InvitationResponse[]>{
    return (await pool.query(
        `SELECT ${ALIAS}.${COLUMN_UUID},${USER_SENDER_ALIAS}.${USER_COLUMN_UUID} as ${ALIAS_SENDER_UUID},${USER_SENDER_ALIAS}.${USER_COLUMN_FIRST_NAME} AS ${ALIAS_SENDER_FIRST_NAME},${USER_SENDER_ALIAS}.${USER_COLUMN_LAST_NAME} AS ${ALIAS_SENDER_LAST_NAME},${USER_SENDER_ALIAS}.${USER_COLUMN_EMAIL} AS ${ALIAS_SENDER_EMAIL},${USER_SENDER_ALIAS}.${USER_COLUMN_PROFILE_PICTURE_PATH} AS ${ALIAS_SENDER_PROFILE_PICTURE_PATH},${USER_RECIPIENT_ALIAS}.${USER_COLUMN_UUID} AS ${ALIAS_RECIPIENT_UUID},${USER_RECIPIENT_ALIAS}.${USER_COLUMN_FIRST_NAME} AS ${ALIAS_RECIPIENT_FIRST_NAME},${USER_RECIPIENT_ALIAS}.${USER_COLUMN_LAST_NAME} AS ${ALIAS_RECIPIENT_LAST_NAME},${USER_RECIPIENT_ALIAS}.${USER_COLUMN_EMAIL} AS ${ALIAS_RECIPIENT_EMAIL},${USER_RECIPIENT_ALIAS}.${USER_COLUMN_PROFILE_PICTURE_PATH} AS ${ALIAS_RECIPIENT_PROFILE_PICTURE_PATH},${ORGANIZATION_ALIAS}.${ORGANIZATION_COLUMN_UUID} AS ${ORGANIZATION_ALIAS_COLUMN_UUID},${ORGANIZATION_ALIAS}.${ORGANIZATION_COLUMN_NAME} as ${ORGANIZATION_ALIAS_COLUMN_NAME},${ORGANIZATION_ALIAS}.${COLUMN_PROFILE_PICTURE_PATH} AS ${ORGANIZATION_ALIAS_COLUMN_PROFILE_PICTURE_PATH},${ALIAS}.${COLUMN_CREATED_AT_UTC} AS ${ALIAS_COLUMN_CREATED_AT_UTC},${ALIAS}.${COLUMN_EXPIRES_AT_UTC} AS ${ALIAS_COLUMN_EXPIRES_AT_UTC},${ALIAS}.${COLUMN_INVITATION_STATUS}
         FROM ${TABLE_NAME} ${ALIAS}
         LEFT JOIN ${USER_TABLE_NAME} ${USER_SENDER_ALIAS} ON ${ALIAS}.${COLUMN_SENDER_ID}=${USER_SENDER_ALIAS}.${USER_COLUMN_ID}
         LEFT JOIN ${USER_TABLE_NAME} ${USER_RECIPIENT_ALIAS} ON ${ALIAS}.${COLUMN_RECIPIENT_EMAIL}=${USER_RECIPIENT_ALIAS}.${USER_COLUMN_EMAIL}
         INNER JOIN ${ORGANIZATION_TABLE_NAME} ${ORGANIZATION_ALIAS} ON ${USER_SENDER_ALIAS}.${USER_COLUMN_ORGANIZATION_ID}=${ORGANIZATION_ALIAS}.${ORGANIZATION_COLUMN_ID}
         WHERE ${ORGANIZATION_ALIAS}.${ORGANIZATION_COLUMN_UUID}=$1`,
        [organizationUuid])).rows;
}

export async function findByUuid(organizationUuid:string,invitationUuid:string):Promise<InvitationResponse>{
    return (await pool.query(
        `SELECT ${ALIAS}.${COLUMN_UUID},${USER_SENDER_ALIAS}.${USER_COLUMN_UUID} as ${ALIAS_SENDER_UUID},${USER_SENDER_ALIAS}.${USER_COLUMN_FIRST_NAME} AS ${ALIAS_SENDER_FIRST_NAME},${USER_SENDER_ALIAS}.${USER_COLUMN_LAST_NAME} AS ${ALIAS_SENDER_LAST_NAME},${USER_SENDER_ALIAS}.${USER_COLUMN_EMAIL} AS ${ALIAS_SENDER_EMAIL},${USER_SENDER_ALIAS}.${USER_COLUMN_PROFILE_PICTURE_PATH} AS ${ALIAS_SENDER_PROFILE_PICTURE_PATH},${USER_RECIPIENT_ALIAS}.${USER_COLUMN_UUID} AS ${ALIAS_RECIPIENT_UUID},${USER_RECIPIENT_ALIAS}.${USER_COLUMN_FIRST_NAME} AS ${ALIAS_RECIPIENT_FIRST_NAME},${USER_RECIPIENT_ALIAS}.${USER_COLUMN_LAST_NAME} AS ${ALIAS_RECIPIENT_LAST_NAME},${USER_RECIPIENT_ALIAS}.${USER_COLUMN_EMAIL} AS ${ALIAS_RECIPIENT_EMAIL},${USER_RECIPIENT_ALIAS}.${USER_COLUMN_PROFILE_PICTURE_PATH} AS ${ALIAS_RECIPIENT_PROFILE_PICTURE_PATH},${ORGANIZATION_ALIAS}.${ORGANIZATION_COLUMN_UUID} AS ${ORGANIZATION_ALIAS_COLUMN_UUID},${ORGANIZATION_ALIAS}.${ORGANIZATION_COLUMN_NAME} as ${ORGANIZATION_ALIAS_COLUMN_NAME},${ORGANIZATION_ALIAS}.${COLUMN_PROFILE_PICTURE_PATH} AS ${ORGANIZATION_ALIAS_COLUMN_PROFILE_PICTURE_PATH},${ALIAS}.${COLUMN_CREATED_AT_UTC} AS ${ALIAS_COLUMN_CREATED_AT_UTC},${ALIAS}.${COLUMN_EXPIRES_AT_UTC} AS ${ALIAS_COLUMN_EXPIRES_AT_UTC},${ALIAS}.${COLUMN_INVITATION_STATUS}
         FROM ${TABLE_NAME} ${ALIAS}
         LEFT JOIN ${USER_TABLE_NAME} ${USER_SENDER_ALIAS} ON ${ALIAS}.${COLUMN_SENDER_ID}=${USER_SENDER_ALIAS}.${USER_COLUMN_ID}
         LEFT JOIN ${USER_TABLE_NAME} ${USER_RECIPIENT_ALIAS} ON ${ALIAS}.${COLUMN_RECIPIENT_EMAIL}=${USER_RECIPIENT_ALIAS}.${USER_COLUMN_EMAIL}
         INNER JOIN ${ORGANIZATION_TABLE_NAME} ${ORGANIZATION_ALIAS} ON ${USER_SENDER_ALIAS}.${USER_COLUMN_ORGANIZATION_ID}=${ORGANIZATION_ALIAS}.${ORGANIZATION_COLUMN_ID}
         WHERE ${ORGANIZATION_ALIAS}.${ORGANIZATION_COLUMN_UUID}=$1 AND ${ALIAS}.${COLUMN_UUID} = $2`,
        [organizationUuid,invitationUuid])).rows[0]
}

export async function create(invitation: CreateInvitation):Promise<Invitation> {
    return (await pool.query(
        `INSERT INTO ${TABLE_NAME}(${COLUMN_SENDER_ID},${COLUMN_RECIPIENT_EMAIL},${COLUMN_EXPIRES_AT_UTC})
                    VALUES ($1,$2,$3)
                    RETURNING ${COLUMN_UUID},${COLUMN_CREATED_AT_UTC},${COLUMN_EXPIRES_AT_UTC},${COLUMN_INVITATION_STATUS}`,
        [invitation.senderId, invitation.email,invitation.expiresAtUTC])).rows[0];
}

export async function update(invitation:UpdateInvitation):Promise<Invitation> {
    return (await pool.query(
        `UPDATE ${TABLE_NAME}
         SET ${COLUMN_INVITATION_STATUS}=$1
         WHERE ${COLUMN_UUID} = $2
         RETURNING ${COLUMN_UUID},${COLUMN_CREATED_AT_UTC},${COLUMN_EXPIRES_AT_UTC},${COLUMN_INVITATION_STATUS}`,
        [invitation.status,invitation.uuid])).rows[0];
}